<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Enrollment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class EnrollmentController extends Controller
{
    /**
     * Get all enrollments
     */
    public function index(Request $request)
    {
        $enrollments = Enrollment::with('user', 'course')->paginate(15);

        return response()->json([
            'success' => true,
            'data' => $enrollments,
            'message' => 'All enrollments',
        ]);
    }

    /**
     * Create enrollment from registration form
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'user_id' => 'required|exists:users,id',
            'class_type_id' => 'required|exists:class_types,id',
            'phone' => 'nullable|string|max:50',
            'city' => 'nullable|string|max:100',
            'native_language' => 'nullable|string|max:100',
            'english_level' => 'nullable|string|max:50',
            'french_level' => 'nullable|string|max:50',
            'course_purpose' => 'nullable|string',
            'special_request' => 'nullable|string',
            'referral_source' => 'nullable|string|max:255',
            'coupon_code' => 'nullable|string',
            'discount_amount' => 'nullable|numeric|min:0',
            'final_amount' => 'required|numeric|min:0',
            'availability' => 'nullable|string',
        ]);

        // Entry ID will be auto-generated by the model's boot method
        $enrollment = Enrollment::create([
            'user_id' => $validated['user_id'],
            'class_type_id' => $validated['class_type_id'],
            'status' => 'pending', // Will be updated to 'active' after payment
            'enrollment_date' => now(),
            // Store additional form data as JSON (model will auto-cast to JSON)
            'form_data' => [
                'phone' => $validated['phone'] ?? null,
                'city' => $validated['city'] ?? null,
                'native_language' => $validated['native_language'] ?? null,
                'english_level' => $validated['english_level'] ?? null,
                'french_level' => $validated['french_level'] ?? null,
                'course_purpose' => $validated['course_purpose'] ?? null,
                'special_request' => $validated['special_request'] ?? null,
                'referral_source' => $validated['referral_source'] ?? null,
                'coupon_code' => $validated['coupon_code'] ?? null,
                'discount_amount' => $validated['discount_amount'] ?? 0,
                'final_amount' => $validated['final_amount'],
                'availability' => $validated['availability'] ?? null,
            ],
        ]);

        return response()->json([
            'success' => true,
            'data' => [
                'enrollment_id' => $enrollment->id,
                'amount' => $validated['final_amount'],
                'coupon_code' => $validated['coupon_code'] ?? null,
                'discount_amount' => $validated['discount_amount'] ?? 0,
            ],
            'message' => 'Enrollment created. Proceed to payment.',
        ], 201);
    }

    /**
     * Get enrollment detail
     */
    public function show(string $id)
    {
        $enrollment = Enrollment::with('user', 'course')->findOrFail($id);

        return response()->json([
            'success' => true,
            'data' => $enrollment,
            'message' => 'Enrollment detail',
        ]);
    }

    /**
     * Update enrollment
     */
    public function update(Request $request, string $id)
    {
        $enrollment = Enrollment::findOrFail($id);

        $validated = $request->validate([
            'status' => 'nullable|string|in:active,completed,cancelled',
            'class_type_id' => 'nullable|exists:class_types,id',
        ]);

        $enrollment->update($validated);

        return response()->json([
            'success' => true,
            'data' => $enrollment,
            'message' => 'Enrollment updated',
        ]);
    }

    /**
     * Delete enrollment
     */
    public function destroy(string $id)
    {
        $enrollment = Enrollment::findOrFail($id);
        $enrollment->delete();

        return response()->json([
            'success' => true,
            'message' => 'Enrollment deleted',
        ]);
    }
}
